
default: &DEFAULTS
  app: &APP_DEFAULTS
    scheme: GovUK-UIComponents
    workspace: GovUK-UIComponents.xcworkspace
    project: Example/GovUK-UIComponents.xcodeproj
    test_plan: UIComponents
  scan:
    output_directory: test_output
    devices:
      - iPhone 16 Pro (18.2)

unit:
  <<: *DEFAULTS
